export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  portalOwnerAccessToken: process.env.PORTAL_OWNER_ACCESS_TOKEN ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  isProduction: process.env.NODE_ENV === "production",
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID ?? "",
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY ?? "",
  awsSessionToken: process.env.AWS_SESSION_TOKEN ?? "",
  bedrockApiKey: process.env.BEDROCK_API_KEY ?? process.env.AWS_BEARER_TOKEN_BEDROCK ?? "",
  bedrockRegion: process.env.BEDROCK_REGION ?? process.env.AWS_REGION ?? "",
  bedrockModelId: process.env.BEDROCK_MODEL_ID ?? "",
  bedrockMaxTokens: Number(process.env.BEDROCK_MAX_TOKENS ?? 4096),
  bedrockTemperature: Number(process.env.BEDROCK_TEMPERATURE ?? 0.1),
  bedrockTopP: Number(process.env.BEDROCK_TOP_P ?? 0.9),
  bedrockTimeoutMs: Number(process.env.BEDROCK_TIMEOUT_MS ?? 60000),
  portalS3Bucket: process.env.PORTAL_S3_BUCKET ?? "",
  portalS3Region: process.env.PORTAL_S3_REGION ?? process.env.AWS_REGION ?? "",
};
